<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;

class EaConfiguration extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'account_id',
        'active_strategy',
        'timeframe_logic',
        'pair_symbol',
        'grid_max_layers',
        'grid_max_accumulative_lot',
        'grid_target_usd',
        'grid_tp_points',
        'grid_sl_points',
        'grid_use_trailing_layer1',
        'grid_use_basket_tp_percent',
        'grid_basket_tp_percent',
        'grid_tp_mode',
        'grid_tier1_tp_percent',
        'grid_tier2_tp_percent',
        'grid_tier3_tp_percent',
        'grid_tier4_tp_percent',
        'mirror_active',
        'mirror_pending_distance_points',
        'mirror_multiplier',
        'zero_gap_tp_points',
        'zero_gap_sl_points',
        'zero_gap_max_layers',
        'zero_gap_trailing_start_points',
        'zero_gap_trailing_step_points',
        'mart_max_steps',
        'mart_tp_points',
        'mart_sl_points',
        'mart_trailing_start_points',
        'mart_trailing_step_points',
        'filter_snr_activation',
        'news_filter_severity',
        'news_pause_before_minutes',
        'news_pause_after_minutes',
        'live_floating_pnl',
        'live_open_layers',
        'live_guard_status',
        'max_layers',
        'max_accumulative_lot',
        'base_lot',
        'account_currency',
        'max_spread',
        'max_drawdown_pct',
        'max_drawdown_stop_delay',
        'daily_profit_target',
        'use_martingale',
        'target_tp_percentage',
        'mart_type',
        'mart_addition',
        'mart_multiplier',
        'grid_mode',
        'fix_grid_distance',
        'atr_period_grid',
        'atr_timeframe_grid',
        'atr_multiplier',
        'min_grid_distance',
        'farming_gap',
        'mart_start_layer',
        'initial_sl',
        'trail_start',
        'trail_stop',
        'trail_step',
        'use_breakeven',
        'be_distance',
        'be_buffer',
        'start_hour',
        'end_hour',
        'always_in_market',
        'instant_reentry',
        'min_confluence_score',
        'auto_flip',
        'use_pending_guard',
        'use_trend_filter',
        'use_ai_core_sharpening',
        'use_ema_ribbon',
        'use_dmi',
        'use_mkt_struct',
        'use_early_trend',
        'use_sniper_entry',
        'bb_period',
        'bb_deviation',
        'rsi_period',
        'rsi_buy_level',
        'rsi_sell_level',
        'adx_period',
        'adx_level',
        'adx_bars',
        'adx_sideways',
        'ema_period',
        'ema_fast',
        'ema_slow',
        'ema_slope_min',
        'atr_period',
        'use_dxy_filter',
        'close_all_on_news',
        'show_indicator_fallback_logs',
        'use_mirror_trap',
        'use_stealth_mode',
        'use_sydney_session',
        'sydney_start_wib',
        'sydney_end_wib',
        'use_asia_session',
        'asia_start_wib',
        'asia_end_wib',
        'use_europe_session',
        'europe_start_wib',
        'europe_end_wib',
        'use_us_session',
        'us_start_wib',
        'us_end_wib',
        'current_layers',
        'current_accumulative_lot',
        'global_floating',
        'guard_status',
        'is_online',
    ];

    protected $casts = [
        'pair_symbol' => 'string',
        'active_strategy' => 'integer',
        'timeframe_logic' => 'integer',
        'grid_max_layers' => 'integer',
        'grid_max_accumulative_lot' => 'float',
        'grid_target_usd' => 'float',
        'grid_tp_points' => 'integer',
        'grid_sl_points' => 'integer',
        'grid_use_trailing_layer1' => 'boolean',
        'grid_use_basket_tp_percent' => 'boolean',
        'grid_basket_tp_percent' => 'float',
        'grid_tp_mode' => 'integer',
        'grid_tier1_tp_percent' => 'float',
        'grid_tier2_tp_percent' => 'float',
        'grid_tier3_tp_percent' => 'float',
        'grid_tier4_tp_percent' => 'float',
        'mirror_active' => 'boolean',
        'mirror_pending_distance_points' => 'integer',
        'mirror_multiplier' => 'float',
        'zero_gap_tp_points' => 'integer',
        'zero_gap_sl_points' => 'integer',
        'zero_gap_max_layers' => 'integer',
        'zero_gap_trailing_start_points' => 'integer',
        'zero_gap_trailing_step_points' => 'integer',
        'mart_max_steps' => 'integer',
        'mart_tp_points' => 'integer',
        'mart_sl_points' => 'integer',
        'mart_trailing_start_points' => 'integer',
        'mart_trailing_step_points' => 'integer',
        'filter_snr_activation' => 'boolean',
        'news_filter_severity' => 'string',
        'news_pause_before_minutes' => 'integer',
        'news_pause_after_minutes' => 'integer',
        'live_floating_pnl' => 'float',
        'live_open_layers' => 'integer',
        'live_guard_status' => 'string',
        'max_layers' => 'integer',
        'max_accumulative_lot' => 'float',
        'base_lot' => 'float',
        'account_currency' => 'string',
        'max_spread' => 'integer',
        'max_drawdown_pct' => 'float',
        'max_drawdown_stop_delay' => 'integer',
        'daily_profit_target' => 'float',
        'use_martingale' => 'boolean',
        'target_tp_percentage' => 'float',
        'mart_type' => 'integer',
        'mart_addition' => 'float',
        'mart_multiplier' => 'float',
        'grid_mode' => 'integer',
        'fix_grid_distance' => 'integer',
        'atr_period_grid' => 'integer',
        'atr_timeframe_grid' => 'integer',
        'atr_multiplier' => 'float',
        'min_grid_distance' => 'integer',
        'farming_gap' => 'float',
        'mart_start_layer' => 'integer',
        'initial_sl' => 'float',
        'trail_start' => 'float',
        'trail_stop' => 'float',
        'trail_step' => 'float',
        'use_breakeven' => 'boolean',
        'be_distance' => 'float',
        'be_buffer' => 'float',
        'start_hour' => 'integer',
        'end_hour' => 'integer',
        'always_in_market' => 'boolean',
        'instant_reentry' => 'boolean',
        'min_confluence_score' => 'integer',
        'auto_flip' => 'boolean',
        'use_pending_guard' => 'boolean',
        'use_trend_filter' => 'boolean',
        'use_ai_core_sharpening' => 'boolean',
        'use_ema_ribbon' => 'boolean',
        'use_dmi' => 'boolean',
        'use_mkt_struct' => 'boolean',
        'use_early_trend' => 'boolean',
        'use_sniper_entry' => 'boolean',
        'bb_period' => 'integer',
        'bb_deviation' => 'float',
        'rsi_period' => 'integer',
        'rsi_buy_level' => 'float',
        'rsi_sell_level' => 'float',
        'adx_period' => 'integer',
        'adx_level' => 'float',
        'adx_bars' => 'integer',
        'adx_sideways' => 'float',
        'ema_period' => 'integer',
        'ema_fast' => 'integer',
        'ema_slow' => 'integer',
        'ema_slope_min' => 'float',
        'atr_period' => 'integer',
        'use_dxy_filter' => 'boolean',
        'close_all_on_news' => 'boolean',
        'show_indicator_fallback_logs' => 'boolean',
        'use_mirror_trap' => 'boolean',
        'use_stealth_mode' => 'boolean',
        'use_sydney_session' => 'boolean',
        'sydney_start_wib' => 'string',
        'sydney_end_wib' => 'string',
        'use_asia_session' => 'boolean',
        'asia_start_wib' => 'string',
        'asia_end_wib' => 'string',
        'use_europe_session' => 'boolean',
        'europe_start_wib' => 'string',
        'europe_end_wib' => 'string',
        'use_us_session' => 'boolean',
        'us_start_wib' => 'string',
        'us_end_wib' => 'string',
        'current_layers' => 'integer',
        'current_accumulative_lot' => 'float',
        'global_floating' => 'float',
        'is_online' => 'boolean',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function license(): HasOne
    {
        return $this->hasOne(Mt5AccountLicense::class, 'account_id', 'account_id');
    }
}
